# Generated by Django 3.1.7 on 2021-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bell',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ring',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
