# Generated by Django 3.1.7 on 2021-05-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210430_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bell',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ring',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
